### ISSUE TITLE
drawio woes

### ISSUE THREAD

**Issue by rontrompert** [tomneedham/oc-drawio#10]
Hi Tom,

Today we ran into a peculiar issue. Recently we have enable the drawio
app. But when you upload a file having a name with no extentions, so
just a file name, and you click on the file in the web browser, drawio
opens and reports an error that it is not a diagram. Instead it should
just download the file. Can this be fixed? We run 10.0.9 enterprise.

Cheers,

Ron

**Comment by tomneedham** [comment]
Duplicate https://github.com/tomneedham/oc-drawio/issues/8
