### ISSUE TITLE
This content is blocked. Contact the site owner to fix the issue - oc-drawio v0.0.8 and OwnCloud v10.5.xx

### ISSUE THREAD

**Issue by kzsolt76** [tomneedham/oc-drawio#16]
To enable oc-drawio v0.0.8 in OwnCloud v10.5.xx and to fix "This content is blocked. Contact the site owner to fix the issue." issue make the following changes:

Step 1 - {OWNCLOUD}/apps-external/drawio/appinfo/info.xml
<owncloud min-version="10.0" max-version="10.5" />

Step 2- {OWNCLOUD}/apps-external/drawio/templates/editor.php
'https://www.draw.io' => 'https://embed.diagrams.net'

Step 3 - {OWNCLOUD}/apps-external/drawio/lib/Controller/PageController.php
SERVERURL = 'https://www.draw.io'  => 'https://embed.diagrams.net';

**Comment by tomneedham** [comment]
Fixed in https://github.com/tomneedham/oc-drawio/pull/15
